In [3]:
import pandas as pd

In [4]:
import matplotlib .pyplot as plt

In [5]:
df = pd.read_csv("C:/Users/ELCOT/Downloads/date_time_dataset-1.csv")

In [6]:
df.head()

         Date      Time  Temperature  Humidity  Sales
0  2026-01-01  08:00:00           24        65    120
1  2026-01-01  18:30:00           27        58    180
2  2026-01-02  09:15:00           23        70    110
3  2026-01-02  20:00:00           25        62    165
4  2026-01-03  07:45:00           22        75     95

In [7]:
df.tail()

         Date      Time  Temperature  Humidity  Sales
5  2026-01-03  17:30:00           26        60    155
6  2026-01-04  10:00:00           24        68    130
7  2026-01-04  19:15:00           28        55    190
8  2026-01-05  08:30:00           23        72    105
9  2026-01-05  21:00:00           26        57    175

In [8]:
df.size

50

In [9]:
df.shape

(10, 5)

In [10]:
print(df.columns)

Index(['Date', 'Time', 'Temperature', 'Humidity', 'Sales'], dtype='str')

In [12]:
df.isnull()

    Date   Time  Temperature  Humidity  Sales
0  False  False        False     False  False
1  False  False        False     False  False
2  False  False        False     False  False
3  False  False        False     False  False
4  False  False        False     False  False
5  False  False        False     False  False
6  False  False        False     False  False
7  False  False        False     False  False
8  False  False        False     False  False
9  False  False        False     False  False

In [13]:
df.isnull().sum()

Date           0
Time           0
Temperature    0
Humidity       0
Sales          0
dtype: int64

In [14]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.dropna(inplace = True)

In [18]:

df["Transaction Date"] = pd.to_datetime(df["Transaction Date"])

KeyError: 'Transaction Date'

In [19]:
df.head()

         Date      Time  Temperature  Humidity  Sales
0  2026-01-01  08:00:00           24        65    120
1  2026-01-01  18:30:00           27        58    180
2  2026-01-02  09:15:00           23        70    110
3  2026-01-02  20:00:00           25        62    165
4  2026-01-03  07:45:00           22        75     95

In [20]:
df.loc[0]
df.loc[0:4]

         Date      Time  Temperature  Humidity  Sales
0  2026-01-01  08:00:00           24        65    120
1  2026-01-01  18:30:00           27        58    180
2  2026-01-02  09:15:00           23        70    110
3  2026-01-02  20:00:00           25        62    165
4  2026-01-03  07:45:00           22        75     95

In [21]:
df.iloc[0:9]

         Date      Time  Temperature  Humidity  Sales
0  2026-01-01  08:00:00           24        65    120
1  2026-01-01  18:30:00           27        58    180
2  2026-01-02  09:15:00           23        70    110
3  2026-01-02  20:00:00           25        62    165
4  2026-01-03  07:45:00           22        75     95
5  2026-01-03  17:30:00           26        60    155
6  2026-01-04  10:00:00           24        68    130
7  2026-01-04  19:15:00           28        55    190
8  2026-01-05  08:30:00           23        72    105

In [23]:
df[df["Sales"] < 2000]
df[df["Sales"] >= 2000]
df[df["Sales"] <= 2000]
df[df["Sales"] == 2000]
df[df["Sales"] != 2000]

         Date      Time  Temperature  Humidity  Sales
0  2026-01-01  08:00:00           24        65    120
1  2026-01-01  18:30:00           27        58    180
2  2026-01-02  09:15:00           23        70    110
3  2026-01-02  20:00:00           25        62    165
4  2026-01-03  07:45:00           22        75     95
5  2026-01-03  17:30:00           26        60    155
6  2026-01-04  10:00:00           24        68    130
7  2026-01-04  19:15:00           28        55    190
8  2026-01-05  08:30:00           23        72    105
9  2026-01-05  21:00:00           26        57    175

In [25]:
df["new"] = df["Sales"] * 2
print(df)

         Date      Time  Temperature  Humidity  Sales  new
0  2026-01-01  08:00:00           24        65    120  240
1  2026-01-01  18:30:00           27        58    180  360
2  2026-01-02  09:15:00           23        70    110  220
3  2026-01-02  20:00:00           25        62    165  330
4  2026-01-03  07:45:00           22        75     95  190
5  2026-01-03  17:30:00           26        60    155  310
6  2026-01-04  10:00:00           24        68    130  260
7  2026-01-04  19:15:00           28        55    190  380
8  2026-01-05  08:30:00           23        72    105  210
9  2026-01-05  21:00:00           26        57    175  350

In [26]:
df.head()

         Date      Time  Temperature  Humidity  Sales  new
0  2026-01-01  08:00:00           24        65    120  240
1  2026-01-01  18:30:00           27        58    180  360
2  2026-01-02  09:15:00           23        70    110  220
3  2026-01-02  20:00:00           25        62    165  330
4  2026-01-03  07:45:00           22        75     95  190

In [27]:
df.groupby("Date")["Sales"].mean()

Date
2026-01-01    150.0
2026-01-02    137.5
2026-01-03    125.0
2026-01-04    160.0
2026-01-05    140.0
Name: Sales, dtype: float64

In [29]:
df['Time'].unique()

<StringArray>
['08:00:00', '18:30:00', '09:15:00', '20:00:00', '07:45:00', '17:30:00',
 '10:00:00', '19:15:00', '08:30:00', '21:00:00']
Length: 10, dtype: str

In [32]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Time_Encoded'] = le.fit_transform(df['Time'])

print(df.head())

         Date      Time  Temperature  Humidity  Sales  new  Time_Encoded
0  2026-01-01  08:00:00           24        65    120  240             1
1  2026-01-01  18:30:00           27        58    180  360             6
2  2026-01-02  09:15:00           23        70    110  220             3
3  2026-01-02  20:00:00           25        62    165  330             8
4  2026-01-03  07:45:00           22        75     95  190             0

In [33]:
le = LabelEncoder()

In [36]:
df["Time2"] = le.fit_transform(df["Time"])

In [37]:
df.head()

,Date,Time,Temperature,Humidity,Sales,new,Time_Encoded,Time2
0,2026-01-01,08:00:00,24,65,120,240,1,1
1,2026-01-01,18:30:00,27,58,180,360,6,6
2,2026-01-02,09:15:00,23,70,110,220,3,3
3,2026-01-02,20:00:00,25,62,165,330,8,8
4,2026-01-03,07:45:00,22,75,95,190,0,0

In [38]:
df=pd.get_dummies(df,columns=["Prod"],dtype=int)
vv.head()

KeyError: "None of [Index(['Prod'], dtype='str')] are in the [columns]"